### ISSUE TITLE
[Bug]: Tracker inconsistency - Early Sparrot's crystal replacement (NOT URGENT)

### ISSUE THREAD

**Issue by AudioOstrich433** [mint-choc-chip-skyblade/sshd-rando#432]
### Discord ID / GitHub Username

AudioOstrich433

### What did you expect to happen?

The tracker says that retrieving Sparrot's (fortune teller) replacement crystal ball (located on top of the earth temple) is unavailable until the digging mitts are obtained
![Screenshot](https://github.com/user-attachments/assets/00718ba3-7834-4153-9af3-75b36e0fd9c6)

### What actually happened?

I was able to reach the target with the clawshots without the digging mitts by using an adjacent ledge that can be climbed.
Obviously not an urgent issue, but I thought that I would bring it up.

### OS

Windows

### Platform

Emulator

### Randomizer Version

1.4

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YourAverageLink** [comment]
This is a deliberate decision, because in the HD version, it can be a bit difficult for a casual player to reach this ledge from the ground (See #245). Thanks for checking, though! If you find anything similar (particularly if you think an item is _missing_ in the requirements), feel free to bring it up again.
